class weblogic::domain (
    $wlsVersion                = undef,
    $wlsHome                   = undef,
    $oraMdwHome                = undef,
    $jdkHome                   = undef,
    $wlsDomainsRoot             = undef,
    $wlsApplicationsRoot       = undef,
    $wlsDomainTemplate         = undef,
    $wlsDomain                 = undef,
    $wlsDevMode                = undef,
    $wlsAdminServerName        = undef,
    $wlsAdminServerAddress     = undef,
    $wlsAdminServerPort        = undef,
    $wlsNodeManagerAddress     = undef,
    $wlsNodeManagerPort        = undef,
    $wlsUser                   = undef,
    $wlsPassword               = undef,
    $oraUser                   = undef,
    $oraGroup                  = undef,
    $downloadDir               = undef,
    $oraLogs                   = undef,
    $oraLogOutput              = undef,
    $wlsCustomTrust            = undef,
    $wlsTrustKSFile            = undef,
    $wlsTrustKSPassphrase      = undef,

  ) {

  orawls::domain {'wls12domain':
    version                   => $wlsVersion,
    weblogic_home_dir         => $wlsHome,
    middleware_home_dir       => $oraMdwHome,
    jdk_home_dir              => $jdkHome,
    wls_domains_dir           => $wlsDomainsRoot,
    wls_apps_dir              => $wlsApplicationsRoot,
    domain_template           => $wlsDomainTemplate,
    domain_name               => $wlsDomain,
    development_mode          => $wlsDevMode,
    adminserver_name          => $wlsAdminServerName,
    adminserver_address       => $wlsAdminServerAddress,
    adminserver_port          => $wlsAdminServerPort,
    nodemanager_address       => $wlsNodeManagerAddress,
    nodemanager_port          => $wlsNodeManagerPort,
    weblogic_user             => $wlsUser,
    weblogic_password         => $wlsPassword,
    os_user                   => $oraUser,
    os_group                  => $oraGroup,
    download_dir              => $downloadDir,
    log_dir                   => $oraLogs,
    log_output                => $oraLogOutput,
    custom_trust              => $wlsCustomTrust,
    trust_keystore_file       => $wlsTrustKSFile,
    trust_keystore_passphrase => $wlsTrustKSPassphrase,
  }

  wls_setting { 'default':
    user              => $oraUser,
    weblogic_home_dir => $wlsHome,
    connect_url       => "t3://${wlsAdminServerAddress}:${wlsAdminServerPort}",
    weblogic_user     => $wlsUser,
    weblogic_password => $wlsPassword,
  }
}
